services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_root_password
      MYSQL_DATABASE: blockchain
      MYSQL_USER: blockchain
      MYSQL_PASSWORD: blockchain123
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - blockchain-network

  blockchain:
    build: .
    container_name: phpblockchain-app
    depends_on:
      - database
    environment:
      PHP_ENV: development
      BLOCKCHAIN_NETWORK: testnet
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: blockchain
      DB_USER: blockchain
      DB_PASSWORD: blockchain123
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/logs
      - ./config:/var/www/html/config
    networks:
      - blockchain-network

  nginx:
    image: nginx:alpine
    depends_on:
      - blockchain
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    networks:
      - blockchain-network

volumes:
  db_data: {}

networks:
  blockchain-network:
    driver: bridge