version: '3.8'

services:
  blockchain:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/logs
    environment:
      - PHP_ENV=production
      - BLOCKCHAIN_NETWORK=mainnet
    depends_on:
      - database
    networks:
      - blockchain-network

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=blockchain123
      - MYSQL_DATABASE=blockchain
      - MYSQL_USER=blockchain
      - MYSQL_PASSWORD=blockchain123
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - blockchain-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blockchain-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - blockchain
    networks:
      - blockchain-network

volumes:
  db_data:
  redis_data:

networks:
  blockchain-network:
    driver: bridge